### ISSUE TITLE
Stacktrace master doesn't build with msvc-9.0

### ISSUE THREAD

**Issue by pdimov** [boostorg/stacktrace#82] opened 2019-10-26 11:30 UTC
This is fixed on develop, the fix just needs to be merged. 1.72 is approaching.

**Comment by pdimov** [comment] 2019-11-06 01:42
Ping?

**Comment by apolukhin** [comment] 2019-11-11 18:07
There's no MSVC-9 regression test runners. Because of that I treat the issue as unimportant, the fix could wait for 1.73

**Comment by apolukhin** [comment] 2020-01-22 20:29
Fixed, merged to master

**Closed by apolukhin** 2020-01-22 20:29 UTC
