### ISSUE TITLE
BOOST_STACKTRACE_USE_WINDBG_CACHED does not work with MinGW

### ISSUE THREAD

**Issue by githubuser0xFFFF** [boostorg/stacktrace#36] opened 2017-11-03 07:47 UTC
We use the MinGW toolchain that ships with the Qt Libraries. This is the output of gcc -v

```
Thread model: posix
gcc version 5.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
```
Using **BOOST_STACKTRACE_USE_WINDBG_CACHED** results in the following compiler error:

```
../boost/stacktrace/detail/frame_msvc.ipp(167): fatal error C1189: #error: Your compiler does not support C++11 thread_local storage. It's impossible to build with BOOST_STACKTRACE_USE_WINDBG_CACHED.
```

These are the compiller settings:

```
 -O0 -g3 -Wall -c -fmessage-length=0 -std=c++14
```

**Comment by apolukhin** [comment] 2017-11-04 20:09
Yes, that's a known behaviour. Exactly what change are you requesting?

**Comment by apolukhin** [comment] 2017-11-05 17:24
Tried to reflect that behaviour in docs in 8ab572d. Is it OK now? You can see the changes [here](http://boostorg.github.io/stacktrace/stacktrace/configuration_and_build.html#stacktrace.configuration_and_build.mingw_specific_notes)

**Comment by githubuser0xFFFF** [comment] 2017-11-05 18:21
Sorry, if I misunderstand something, but the [documentation](http://boostorg.github.io/stacktrace/stacktrace/configuration_and_build.html#stacktrace.configuration_and_build.mingw_specific_notes) says:

> MinGW-w64 users may use the BOOST_STACKTRACE_USE_WINDBG and BOOST_STACKTRACE_USE_WINDBG_CACHED for getting the best results.

But I use a MinGW-w64 compiler and **BOOST_STACKTRACE_USE_WINDBG_CACHED** does not even compile. Have I overlooked something or do I have the wrong compiler?

**Comment by apolukhin** [comment] 2017-11-12 19:40
OK, I've reproduced the issue locally. The issue is related to this comment https://sourceforge.net/p/mingw-w64/bugs/527/#6b1a

In other words, `thread_local` depends on MinGW build. Just dropped the MinGW* mentions in BOOST_STACKTRACE_USE_WINDBG_CACHED description.

See updated [docs here](http://boostorg.github.io/stacktrace/stacktrace/configuration_and_build.html)

**Comment by apolukhin** [comment] 2017-11-24 20:26
Merged the docs to master

**Closed by apolukhin** 2017-11-24 20:26 UTC
